import type { Metadata } from "next";
import { Noto_Serif_JP } from "next/font/google"

import "./globals.css";

const notoSerifJP = Noto_Serif_JP({
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-serif-jp",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSerifJP.variable}`}>
        {children}
      </body>
    </html>
  );
}
